from collections.abc import Iterable
from typing import Protocol

from src.Domain.Aggregate.TripAggregate.trip import Trip
from src.Domain.Aggregate.TripAdvertisementAggregate.TripAdvertisement import TripAdvertisement
from src.application.DTOs.BookSeatOutputDTO import BookSeatOutputDTO


class ConsolePresenter(Protocol):
    """The controller's UI contract, implemented structurally by ConsoleView."""

    def read(self, prompt: str) -> str: ...
    def menu(self) -> None: ...
    def invalid_choice(self) -> None: ...
    def error(self, operation: str, error: Exception) -> None: ...
    def available_trips(self, advertisements: Iterable[TripAdvertisement]) -> None: ...
    def booking(self, result: BookSeatOutputDTO) -> None: ...
    def trip(self, trip: Trip) -> None: ...
    def scheduled(self, trip_number: str) -> None: ...
